# Generated by Django 5.2.1 on 2025-05-22 18:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('ustaz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('salary', models.FloatField()),
                ('job_time', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], default='part_time', max_length=50)),
                ('job_type', models.CharField(choices=[('online', 'Online'), ('home_tutoring', 'Home Tutoring'), ('institute', 'At Institute'), ('hybrid', 'Hybrid')], default='home_tutoring', max_length=50)),
                ('tuition_time', models.CharField(blank=True, help_text="Expected teaching time, e.g. 'Mon-Thu, 5pm-7pm'", max_length=100, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('drafted', 'Drafted'), ('published', 'Published'), ('closed', 'Closed')], default='drafted', max_length=50)),
                ('subjects', models.CharField(max_length=255)),
                ('ustaz_type', models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=10)),
                ('object_id', models.UUIDField()),
                ('is_verified', models.BooleanField(default=False)),
                ('_job_number', models.BigIntegerField(db_column='job_number', editable=False, null=True, unique=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.address')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Job Post',
                'verbose_name_plural': 'Job Posts',
                'db_table': 'job_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UstazJobRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Headline for your tuition offering', max_length=255)),
                ('bio', models.TextField(help_text='Description about your experience, subject expertise, etc.')),
                ('subjects', models.CharField(help_text='Comma-separated subjects (e.g. Math, English)', max_length=255)),
                ('classes', models.CharField(help_text="Class levels you're interested in (e.g. 6-8, SSC)", max_length=255)),
                ('status', models.CharField(choices=[('drafted', 'Drafted'), ('published', 'Published'), ('closed', 'Closed')], default='drafted', max_length=50)),
                ('job_time', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], default='part_time', max_length=50)),
                ('job_type', models.CharField(choices=[('online', 'Online'), ('home_tutoring', 'Home Tutoring'), ('institute', 'At Institute'), ('hybrid', 'Hybrid')], default='home_tutoring', max_length=50)),
                ('tuition_time', models.CharField(blank=True, help_text='Preferred tuition time (e.g. Mon-Fri, 6-8 PM)', max_length=100, null=True)),
                ('expected_salary', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.address')),
                ('ustaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to='ustaz.ustaz')),
            ],
            options={
                'verbose_name': 'Ustaz Job Post',
                'verbose_name_plural': 'Ustaz Job Posts',
                'db_table': 'ustaz_job_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
