# Generated by Django 5.2.1 on 2025-05-15 17:56

import django.db.models.deletion
import organization.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('facebook_page', models.URLField(blank=True, null=True)),
                ('youtube_page', models.URLField(blank=True, null=True)),
                ('head_name', models.CharField(max_length=100)),
                ('head_nid', models.FileField(blank=True, null=True, upload_to=organization.models.Organization.nid_upload_path)),
                ('head_avatar', models.ImageField(blank=True, null=True, upload_to=organization.models.Organization.ha_upload_path)),
                ('teacher_accomodation', models.ImageField(blank=True, null=True, upload_to=organization.models.Organization.ta_upload_path)),
                ('meal_routine', models.ImageField(blank=True, null=True, upload_to=organization.models.Organization.mr_upload_path)),
                ('hoilday_calendar', models.ImageField(blank=True, null=True, upload_to=organization.models.Organization.hc_upload_path)),
                ('rules', models.TextField(blank=True, null=True)),
                ('committee_permission', models.ImageField(blank=True, null=True, upload_to=organization.models.Organization.cp_upload_path)),
                ('pledge', models.ImageField(blank=True, null=True, upload_to=organization.models.Organization.pledge_upload_path)),
                ('is_verified', models.BooleanField(default=False)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'managed': True,
            },
        ),
    ]
