# Generated by Django 5.2.1 on 2025-06-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='house',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
