# Generated by Django 5.2.1 on 2025-10-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jobtype_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='type',
            field=models.CharField(choices=[('Student', 'Student'), ('Guardian', 'Guardian'), ('Organization', 'Organization'), ('Ustaz', 'Ustaz')], default='Student', max_length=15),
        ),
    ]
