# Generated by Django 5.2.1 on 2025-10-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonial_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
