# Generated by Django 5.2.1 on 2025-10-29 17:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobtype_ordering_testimonial_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.JobCategory.image_upload_path)),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
                'db_table': 'job_categories',
            },
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'ordering': ['ordering'], 'verbose_name': 'Job Type', 'verbose_name_plural': 'Job Types'},
        ),
    ]
