# Generated by Django 5.2.1 on 2025-05-16 03:42

import django.db.models.deletion
import ustaz.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ustaz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_date', models.DateField()),
                ('nid_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('birth_certificate_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nid_front', models.ImageField(blank=True, null=True, upload_to=ustaz.models.Ustaz.nid_front_upload_path)),
                ('nid_back', models.ImageField(blank=True, null=True, upload_to=ustaz.models.Ustaz.nid_back_upload_path)),
                ('guardian_permission_letter', models.FileField(blank=True, null=True, upload_to=ustaz.models.Ustaz.gpl_upload_path)),
                ('chairman_certificate', models.FileField(blank=True, null=True, upload_to=ustaz.models.Ustaz.cc_upload_path)),
                ('pledge', models.FileField(blank=True, null=True, upload_to=ustaz.models.Ustaz.pledge_upload_path)),
                ('teacher_appreciation', models.FileField(blank=True, null=True, upload_to=ustaz.models.Ustaz.ta_upload_path)),
                ('is_verified', models.BooleanField(default=False)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ustaz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uztaz',
                'verbose_name_plural': 'Asatizah',
                'db_table': 'asatizah',
            },
        ),
        migrations.CreateModel(
            name='TrainingCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=ustaz.models.TrainingCertificate.file_upload_path)),
                ('ustaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_certificates', to='ustaz.ustaz')),
            ],
            options={
                'db_table': 'training_certificates',
            },
        ),
        migrations.CreateModel(
            name='OrganizationTestimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=ustaz.models.OrganizationTestimonial.file_upload_path)),
                ('ustaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_testimonials', to='ustaz.ustaz')),
            ],
            options={
                'db_table': 'organization_testimonials',
            },
        ),
        migrations.CreateModel(
            name='EducationalQualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=ustaz.models.EducationalQualification.file_upload_path)),
                ('ustaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_qualification', to='ustaz.ustaz')),
            ],
            options={
                'db_table': 'educational_qualifications',
            },
        ),
        migrations.CreateModel(
            name='AchievementCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=ustaz.models.AchievementCertificate.file_upload_path)),
                ('ustaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_certificates', to='ustaz.ustaz')),
            ],
            options={
                'db_table': 'achievement_certificates',
            },
        ),
    ]
